---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "group-du-sno"
  namespace: "ztp-group"
spec:
  bindingRules:
    du-profile: "410"
  mcp: "master"
  sourceFiles:
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      metadata:
        name: openshift-node-performance-profile
      spec:
        additionalKernelArgs:
          - pci=realloc
        cpu:
          isolated: "2-7,10-15"
          reserved: "0-1,8-9"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 8
