---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "sno02"
  namespace: "ztp-site"
spec:
  bindingRules:
    sites: "sno02"
  mcp: "master"
  sourceFiles:
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      metadata:
        name: openshift-node-performance-profile
      spec:
        additionalKernelArgs:
          - pci=realloc
        cpu:
          isolated: "2-7,10-15"
          reserved: "0-1,8-9"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 8
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "policy-x710-0-openshift"
      spec:
        deviceType: netdevice
        isRdma: false
        nicSelector:
          pfNames: ["ens4f0#0-0"]
        numVfs: 9
        resourceName: x710_0_openshift
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "policy-x710-0-vfio-pci"
      spec:
        deviceType: vfio-pci
        isRdma: false
        nicSelector:
          pfNames: ["ens4f0#1-4"]
        numVfs: 9
        resourceName: x710_0_vfio_pci
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "policy-x710-0-netdevice"
      spec:
        deviceType: netdevice
        isRdma: false
        nicSelector:
          pfNames: ["ens4f0#5-8"]
        numVfs: 9
        resourceName: x710_0_netdevice
